
[air]
	#Range: > 1
	uses_per_tank = 7048
	#Range: > 1
	uses_per_tank_hover = 1500

[speed]
	#Range: 0.01 ~ 100.0
	horizontal = 0.01
	#Range: 0.01 ~ 100.0
	vertical = 0.1
	#Range: 0.01 ~ 100.0
	acceleration = 0.1
	#Range: -100.0 ~ 0.0
	hover_descend = -0.03
	#Range: 0.0 ~ 100.0
	swim_modifier = 1.4

[features]
	#Range: 1.0 ~ 100.0
	elytra_boost = 1.25

[enchantments]
	list = []
	is_blacklist = true

