# enabled = default:true, toggles the entire mod
enabled = true
# torches_burn = default:false, toggles damage from torches
torches_burn = false
# soul_torches_burn = default:false, toggles damage from soul torches
soul_torches_burn = false
# campfires_burn = default:true, toggles damage from campfires
campfires_burn = true
# soul_campfires_burn = default:true, toggles damage from soul campfires
soul_campfires_burn = true
# stonecutters_cut = default:true, toggles damage from stonecutters
stonecutters_cut = true
# enable_blaze_damage = default:true, toggles damage from Blaze entities
enable_blaze_damage = true
# enable_magma_cube_damage = default:false, toggles damage from Magma Cube entities
enable_magma_cube_damage = false
# enable_magma_block_damage = default:true, toggles damage from Magma Block's
enable_magma_block_damage = true
