
#Modifiers behaviour
[modifier_behaviour]
	#Shaping
	#Max upgrade slot bonus for Shaping modifier, 3 by default.
	#Range: > 1
	shaping_max_slot = 1
	#How many durability loss is needed for Shaping modifier to gain 1 slot, 500 by default.
	#Range: > 1
	shaping_damages_each_slot = 500
	#Proto Refining
	#Bonus enchantment level each trait level for Proto Refining, 3 by default.
	#Range: > 0
	proto_refining_bonus = 3
	#How many times needed for Proto Refining to gain bonus, 5 by default.
	#Range: > 1
	proto_refining_requirement = 5
	#Radiation Burning and Radioactive Armor
	#Max bonus for Radiation Burning and Radioactive Armor, 0.75 by default.
	#Range: 0.0 ~ 1.0
	irradium_max_bonus = 0.75
	#Radiation amount for Radiation Burning and Radioactive Armor each trait level, 1.0 Sv by default.
	#Range: 0.0 ~ 1.7976931348623157E308
	irradium_radiation_inflict = 1.0
	#Bonus for Radiation Burning and Radioactive Armor each Sv, 0.05 by default.
	#Range: 0.0 ~ 1.0
	irradium_bonus_per_sv = 0.05
	#Fragile
	#Chance for extra durability draw for Fragile Modifier, 0.1 by default.
	#Range: 0.0 ~ 1.0
	fragile_chance = 0.1
	#Extra durability cost for Fragile, 1 by default.
	#Range: > 0
	fragile_cost = 1
	#Reactive Explosive Armor
	#Allows Reactive Explosive Armor Modifier to block explosion and fire damage, true by default.
	reactive_explosive_armor_immunity = true
	#Damage Reduction for Reactive Explosive Armor, 0.25 by default.
	#Range: 0.0 ~ 1.0
	reactive_explosive_armor_reduction = 0.25
	#Nutritive Slime
	#Overslime consumption for each food level, 20 by default.
	#Range: > 0
	nutritive_slime_cost = 20
	#Food level to add each trait level, 1 by default.
	#Range: > 0
	nutritive_slime_recover = 1
	#Return to Slime
	#Overslime recover chance for Return to Slime each trait level, 20% by default.
	#Range: 0.0 ~ 1.0
	return_to_slime_chance = 0.2
	#Generator Modules
	#Basic FE/t for each level of Combustion Generator Module, 200 by default
	#Range: > 0
	combustion_generator_generation = 200
	#Energy per burning time, affects the total FE generated by fuel item. 10 by default, in this case a single coal can produce 16.00 kFE.
	#Range: > 0
	combustion_generator_total_factor = 10
	#Basic FE/t for each level of Overslime Generator Module, 250 by default
	#Range: > 0
	overslime_generator_generation = 250
	#Energy per overslime, 1000 by default.
	#Range: > 0
	overslime_generator_total_factor = 1000
	#Basic FE/t for each level of Piezoelectric Effect modifier, 100 by default
	#Range: > 0
	piezoelectric_effect_generation = 100
	#Energy per damage, 10 by default.
	#Range: > 0
	piezoelectric_effect_generation_per_damage = 10
	#Basic FE/t for each level of Electric Food modifier, 100 by default
	#Range: > 0
	electric_food_consumption = 100
	#Energy per food level, 25kFE by default.
	#Range: > 0
	electric_food_total_consumption = 25000
	#Bonus for Transition Catalyst each trait level, 25% by default.
	#Range: 0.0 ~ 2.147483647E9
	transition_catalyst_bonus = 0.25
	#Bonus for Platinoid Catalyst each trait level, 25% by default.
	#Range: 0.0 ~ 2.147483647E9
	platinoid_catalyst_bonus = 0.25

#Tool Behaviour
[tool_behaviour]
	#Matter Manipulator behaviour
	#Base mining speed multiplier of Matter Manipulator, 1.0 by default.
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_base_multiplier = 1.0
	#Base mining speed multiplier of Matter Manipulator when is conducting AOE mining, 0.5 by default.
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_aoe_base_multiplier = 0.5
	#Mining fluid bonus multiplier of Matter Manipulator , 0.5 by default , meaning that each 200 °C adds 1 mining speed.
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_fluid_bonus_multiplier = 0.5
	#Allows Matter Manipulator to gain enchantment boost from fluids in mining mode (e.g. Gain silk touch from molten emerald). true by default.
	matter_manipulator_fluid_enchanting = true
	#Base mining range for Matter Manipulator, 16.0 by default.
	#Range: 0.0 ~ 64.0
	matter_manipulator_base_range = 16.0
	#Capacity factor for Matter Manipulator, 10.0 by default.
	#Range: 0.0 ~ 2.147483647E9
	ionized_cannon_base_capacity_factor = 10.0
	#Base fluid efficiency for Ionized Cannon, 0.0 by default.
	#Range: 0.0 ~ 2.147483647E9
	ionized_cannon_base_fluid_efficiency = 0.0
	#Ionized Cannon behaviour
	#The multiplier of fluid consumption of Ionized Cannon, 1.0 by default.
	#Range: 0.0 ~ 2.147483647E9
	ionized_cannon_fluid_factor = 1.0
	#Damage multiplier for Ionized Cannon when using correct fluids, 4.0 by default.
	#Range: 1.0 ~ 2.147483647E9
	ionized_cannon_damage_bonus = 4.0
	#Base explosion scale efficiency for Ionized Cannon, 1.0 by default.
	#Range: 0.0 ~ 2.147483647E9
	ionized_cannon_base_scale = 1.0
	#Base attack range for Ionized Cannon, 12.0 by default.
	#Range: 0.0 ~ 2.147483647E9
	ionized_cannon_base_range = 15.0
	#Base duration for Ionized Cannon to charge, 40 ticks by default.
	#Range: > 0
	ionized_cannon_base_duration = 40
	#Electron Tuner behaviour
	#The adjustable range of attack damage for Electron Tuner, 1.5 by default, meaning that the damage can be adjusted within the range of ±0.75 .Note that adjusting this without adjusting electron_tuner_attack_speed_range will greatly affect balance.
	#Range: 0.0 ~ 2.147483647E9
	electron_tuner_damage_range = 1.5
	#The adjustable range of attack damage for Electron Tuner, 1.0 by default, meaning that the damage can be adjusted within the range of ±0.5 .Note that adjusting this without adjusting electron_tuner_damage_range will greatly affect balance.
	#Range: 0.0 ~ 2.147483647E9
	electron_tuner_attack_speed_range = 1.0
	#Allow Electron Tuner to perform special attack , true by default.
	electron_tuner_special = true

#Mekanism Interaction
[mekanism_interaction]
	#Enables fusion reactor exploding when throwing iron ingots into it. true by default.
	allow_neutronite_crafting = true

