#Set to false to disable title fragments from generating as loot.
fragmentLoot = true
#Set to false to disable players from setting nicknames.
nickname = true
#Set to false to prevent holiday starter titles being available
holidayTitles = false

