
[Compatibility]

	[Compatibility.vampirism]
		enable_compat_vampirism = true
		disable_integrations_version_check = false

	[Compatibility.jade]
		enable_compat_jade = false

	[Compatibility.guardvillagers]
		enable_compat_guardvillagers = true

